SET(rcore_io_INST_INCLUDES 
  					     rio.h
                         rtextfile.h
                         rrecfile.h
                         rrecfile.hh
    					 rdownload.h
    					 rfile.h
    					 rdir.h
    					 riofile.h
    					 rbinaryfile.h
						 ruri.h
						 rcsvfile.h
						 rblockfile.h
						 rindexfile.h
)

SET(rcore_io_TARGET_SOURCES 
                               rio.cpp
                               rtextfile.cpp
                               rdownload.cpp
                               rfile.cpp
                               rdir.cpp
                               riofile.cpp
                               rbinaryfile.cpp
               				   ruri.cpp
               				   rcsvfile.cpp 
               				   rblockfile.cpp
               				   rindexfile.cpp
)