SET(roptimization_ga2d_INST_INCLUDES
	rga2d.h
	robj2d.h	
	robj2dconfig.h
	rconnection.h 
    rproblem2d.h
	rgeoinfo.h 
	rlayout.h 
	rgeoinfoconnection.h 
	robj2dcontainer.h 
	rgrid.h
	rfreepolygon.h 
	rfreepolygons.h 
	rplacementheuristic.h
	rplacementbottomleft.h 
	rplacementcenter.h 
	rplacementedge.h 
	rchromo2d.h 
	rchromo2d.hh 
	rga2dimplementation.h 
	rinst2d.h 
	rinst2d.hh 
)


SET(roptimization_ga2d_TARGET_SOURCES
	rga2d.cpp
	robj2d.cpp	
	robj2dconfig.cpp
	rconnection.cpp 
	rproblem2d.cpp
	rgeoinfo.cpp 
	rlayout.cpp 
	rgeoinfoconnection.cpp 
	robj2dcontainer.cpp
	rgrid.cpp		 
	rfreepolygon.cpp 
	rfreepolygons.cpp
	rplacementheuristic.cpp 
	rplacementbottomleft.cpp 
	rplacementcenter.cpp
	rplacementedge.cpp 			                          	
)