SET(rcore_AVAILABLE_FRONTENDS "")
IF(KDE4_FOUND)	
    SET(rcore_AVAILABLE_FRONTENDS kde)
    SET(rcore_kde_DEPENDENCY ${KDE4_KDEUI_LIBS})
    ADD_FRONTEND_SOURCE_FILE(rcore_frontend rcore kde RCORE_INCLUDES)
ENDIF(KDE4_FOUND)
  