SET(rcore_AVAILABLE_FRONTENDS "")
IF(KDE3_FOUND)	
    SET(rcore_AVAILABLE_FRONTENDS ${rcore_AVAILABLE_FRONTENDS} kde)
    SET(rcore_kde_DEPENDENCY ${QT_AND_KDECORE_LIBS})
    ADD_FRONTEND_SOURCE_FILE(rcore_frontend rcore kde RCORE_INCLUDES)
ENDIF(KDE3_FOUND)
  