SET(rmath_matrix_INST_INCLUDES
	rvector.h
	rsparsevector.h
	rgenericmatrix.h
	rmatrix.h
	rsparsematrix.h
	rlowertriangularmatrix.h 
	rsymmetricmatrix.h
	rsparsesymmetricmatrix.h
	rmatrixstorage.h
)
                              
SET(rmath_matrix_TARGET_SOURCES
	rvector.cpp
	rsparsevector.cpp
	rgenericmatrix.cpp
	rmatrix.cpp	
	rsparsematrix.cpp
	rlowertriangularmatrix.cpp
	rsymmetricmatrix.cpp
	rsparsesymmetricmatrix.cpp
	rmatrixstorage.cpp 
)