SET(rcore_app_INST_INCLUDES
	rapplication.h
	rconfig.h
	rparam.h
	rnotification.h
	rnotificationcenter.h
	robject.h
	rthread.h
	rmutex.h
	rconditionvar.h
	rrwlock.h
)

SET(rcore_app_TARGET_SOURCES
	rapplication.cpp
	rconfig.cpp
	rparam.cpp
	rnotification.cpp
	rnotificationcenter.cpp
	robject.cpp
	rthread.cpp
	rmutex.cpp
	rconditionvar.cpp
	rrwlock.cpp
)