SET(rcore_prg_INST_INCLUDES rprgfunc.h 
                       rprginst.h 
                       rprgvarliteral.h 
                       rprgvarref.h
                       rprgvarinst.h
		               rprg.h 
		               rprgclass.h 
		               rprginstfor.h
		               rprginstsub.h
		               rprginstassign.h
		               rprginstblock.h
		               rprginstdelete.h
		               rprginstprint.h  
		               rprgoutput.h
		               rprginstmethod.h 
		               rprgvar.h 
		               rprgvarstring.h
		               rinterpreter.h
		               rprgscope.h
)
		               
SET(rcore_prg_TARGET_SOURCES rprgfunc.cpp 
                          rprginstfor.cpp
                          rprginstsub.cpp
                          rprginstassign.cpp
                          rprginstblock.cpp
		                  rprgvarliteral.cpp 
		                  rprgvarref.cpp
		                  rprgvarinst.cpp 
		                  rprg.cpp 
		                  rprgoutput.cpp
		                  rprgclass.cpp 
		                  rprginst.cpp
		                  rprginstdelete.cpp
		                  rprginstprint.cpp 
		                  rprginstmethod.cpp 
		                  rprgvar.cpp 
		                  rprgvarstring.cpp
		                  rinterpreter.cpp
		                  rprgscope.cpp
)