/*

	R Project Library

	RPrg.h

	Generic script program - Header.

	Copyright 2002-2008 by the Université Libre de Bruxelles.

	Authors:
		Pascal Francq (pfrancq@ulb.ac.be).

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Library General Public
	License as published by the Free Software Foundation; either
	version 2.0 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Library General Public License for more details.

	You should have received a copy of the GNU Library General Public
	License along with this library, as a file COPYING.LIB; if not, write
	to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
	Boston, MA  02111-1307  USA

*/



//------------------------------------------------------------------------------
#ifndef RPrgH
#define RPrgH


//------------------------------------------------------------------------------
// include files for R Project
#include <rtextfile.h>
#include <rcontainer.h>
#include <rcursor.h>


//------------------------------------------------------------------------------
namespace R{
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// forward class declaration
class RPrgOutput;
class RPrgInst;
class RPrgVar;
class RPrgClass;
class RPrg;


//------------------------------------------------------------------------------
/**
* The RPrgException class provides an exception generated by the program.
* @author Pascal Francq
* @short Program Exception.
*/
class RPrgException : public RException
{
	/**
	 * Program that generates the exception.
	 */
	const RPrg* Prg;

public:

	/**
	* Construct an exception.
	* @param prg             Program.
	*/
	RPrgException(const RPrg* prg) throw();

	/**
	* Construct an exception.
	* @param prg             Program.
	* @param str             Message of the error.
	*/
	RPrgException(const RPrg* prg,const char* str) throw();

	/**
	 * Get a pointer to the program generating the error.
	 * @param
	 * @return
	 */
	const RPrg* GetPrg(void) const {return(Prg);}
};


//------------------------------------------------------------------------------
/**
* The RPrg provides a class for executing a script program.
* @author Pascal Francq
* @short Script Program.
*/
class RPrg
{
protected:

	/**
	* Name of the file to execute.
	*/
	R::RString FileName;

	/**
	* Generic output.
	*/
	R::RPrgOutput* Cout;

	/**
	* List of all "Instructions" to execute.
	*/
	R::RContainer<RPrgInst,true,false> Insts;

	/**
	* List of all "Variables" defined in the program.
	*/
	R::RContainer<RPrgVar,true,false> Vars;

	/**
	* List of all "Classes" defined in the program.
	*/
	R::RContainer<RPrgClass,true,false> Classes;

	/**
	* Program file.
	*/
	R::RTextFile Prg;

	/**
	* Temporary string.
	*/
	RString buf;

	/**
	* Must a line be read;
	*/
	bool ReadLine;

	/**
	 * Number of the line where the last instruction begins.
	 */
	size_t Line;

public:

	/**
	* Constructor of a program.
	* @param f              Name of the file.
	* @param o              Output.
	*/
	RPrg(R::RString f,RPrgOutput* o);

	/**
	* Load the script file.
	*/
	void Load(void);

protected :

	/**
	* Count the number of tabs at the begin of a line of source code.
	* @param line           Line to analyze.
	* @returns size_t.
	*/
	static size_t CountTabs(const RString& line);

public:

	/**
	 * Return a string of the form "filename(line)" representing the current
	 * element treated.
	 */
	RString WhatTreated(void) const;

	/**
	 * Get the line number where the last instruction begins.
	 */
	size_t GetNbLine(void) const {return(Line);}

	/**
	* Analyze a line of source code.
	* @param prg            File containing the program.
	* @returns Instruction to insert.
	*/
	RPrgInst* AnalyseLine(R::RTextFile& prg);

	/**
	* Analyze a parameter.
	* @param params         Parameter to analyze.
	* @param values         Values of the parameter.
	*/
	static void AnalyseParam(const RString& params,RContainer<RPrgVar,true,false>* values);

	/**
	* Execute a "program".
	*/
	void Exec(void);

	/**
	* Add a variable.
	* @param var             Pointer to the variable.
	*/
	void AddVar(RPrgVar* var);

	/**
	* Remove a variable.
	* @param var             Pointer to the variable.
	*/
	void DelVar(RPrgVar* var);

	/**
	* Get the value of the variable.
	* @param var            Name of the variable.
	*/
	virtual RString GetValue(const RString& var);

	/**
	* Add a class.
	* @param c               Pointer to the class.
	*/
	void AddVar(RPrgClass* c);

	/**
	* Remove a class.
	* @param c               Pointer to the class.
	*/
	void DelVar(RPrgClass* c);

	/**
	* Get a cursor over the classes.
	*/
	RCursor<RPrgClass> GetClasses(void) const;

	/**
	 * Get the name of the program.
	 */
	RString GetFileName(void) const {return(FileName);}

	/**
	* Destruct of the program.
	*/
	virtual ~RPrg(void);
};


}  //-------- End of namespace R -----------------------------------------------


//------------------------------------------------------------------------------
#endif
