/*
	R Project Library

	QXMLContainer.h

	Qt XML Debugger - Header.

	Copyright 2000-2008 by the Université Libre de Bruxelles.

	Authors:
		Pascal Francq (pfrancq@ulb.ac.be).

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Library General Public
	License as published by the Free Software Foundation; either
	version 2.0 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Library General Public License for more details.

	You should have received a copy of the GNU Library General Public
	License along with this library, as a file COPYING.LIB; if not, write
	to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
	Boston, MA  02111-1307  USA
*/



//------------------------------------------------------------------------------
#ifndef QXMLContainerH
#define QXMLContainerH


//------------------------------------------------------------------------------
// include files for R Project
#include <rdebug.h>


//------------------------------------------------------------------------------
// include files for Qt
#include <QtGui/QTreeWidget>


//------------------------------------------------------------------------------
namespace R{
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
/**
* The QXMLContainer class provides a widget to display debug information
* generated by the GA has XML output.
* @author Pascal Francq.
* @short XML Debug Qt Widget.
*/
class QXMLContainer : public QTreeWidget, public RDebug
{
	Q_OBJECT

	/**
	* The array is used to manage the deepest of the XML structure.
	*/
	QTreeWidgetItem* Items[50];

public:

	/**
	* Construct the XML debug widget.
	* @param parent         Parent of the widget.
	*/
	QXMLContainer(QWidget* parent=0);

	/**
	* Clear the XML.
	*/
	virtual void clear(void);

protected:

	/**
	* Begin a Tag.
	* @param tag            Name of the tag.
	* @param options        Options of the tag.
	*/
	virtual void WriteBeginTag(RString tag,RString options=RString::Null);

	/**
	* Write Text associate with current tag.
	* @param text           Text to write.
	*/
	virtual void WriteText(RString text);

	/**
	* End a Tag.
	* @param tag            Name of the tag.
	*/
	virtual void WriteEndTag(RString tag);

signals:

	/**
	* Emit a signal when this widget is closed.
	*/
	void signalXMLClose(void);

public:

	/**
	* Destruct the XML debug widget.
	*/
	~QXMLContainer(void);
};


}  //------- End of namespace R ------------------------------------------------


//------------------------------------------------------------------------------
#endif
