IF(disable-mysql)
    SET(rcore_db_INST_INCLUDES "")
    SET(rcore_db_TARGET_SOURCES "")
ELSE(disable-mysql)
    SET(rcore_db_INST_INCLUDES rdb.h)
    SET(rcore_db_TARGET_SOURCES rdb.cpp)
ENDIF(disable-mysql)
